name = "ayilon-office"
main = "worker/index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "ayilon-db"
database_id = "REPLACE_WITH_YOUR_DB_ID"

[triggers]
crons = ["* * * * *"]
